-- Strings.lua
-- Place in: ReplicatedStorage as ModuleScript named "Strings"
-- Central Hebrew string table. All UI text is sourced from here.

return {
	Lobby = {
		Welcome          = "ברוכים הבאים ל-Island Survival",
		Instruction      = "עלו על הפלטפורמה הכתומה כדי להתחיל",
		WaitingPlayers   = "ממתינים לשחקנים נוספים...",
		CountdownStart   = "המשחק יתחיל בעוד %d שניות",
		Boarding         = "עולים על המטוס...",
		StepOff          = "ירדו מהפלטפורמה כדי לבטל",
		PlayersReady     = "%d / %d שחקנים מוכנים",
	},
	Flight = {
		TakeOff          = "ממריאים!",
		EngineFailure    = "תקלה במנוע! נופלים!",
		Crash            = "התרסקות!",
	},
	Round = {
		Survived         = "שרדת %d שניות",
		XPGained         = "+%d XP",
		AnimalKilled     = "הרגת %s! +%d XP",
		AllDead          = "כל השחקנים מתו",
		Returning        = "חוזרים ללובי בעוד %d שניות",
		RoundStart       = "הקרב מתחיל!",
	},
	HUD = {
		HP               = "בריאות",
		XP               = "ניסיון",
		Weapon           = "נשק",
		Time             = "זמן",
		ShopHint         = "לחצו B לחנות",
	},
	Shop = {
		Title            = "חנות",
		Close            = "סגור",
		TabWeapons       = "נשקים",
		TabUpgrades      = "שדרוגי טיסה",
		Buy              = "קנה",
		Owned            = "ברשותך",
		Locked           = "נעול",
		BuyRobux         = "קנה ב-Robux",
		BuyXP            = "קנה ב-XP",
		MaxLevel         = "רמה מקסימלית",
		NotEnoughXP      = "אין מספיק XP",
		Purchased        = "נרכש בהצלחה!",
		Level            = "רמה %d",
		Damage           = "נזק: %d",
		Cooldown         = "קצב: %.2f שניות",
		Range            = "טווח: %d studs",
		Price            = "מחיר: %d XP",
		PriceRobux       = "מחיר: %d Robux",
		WeaponSession    = "נשק זמני (סבב נוכחי)",
		WeaponPermanent  = "נשק קבוע (Robux)",
	},
	Death = {
		Title            = "מתת",
		KilledBy         = "נהרגת על ידי %s",
		ReviveBtn        = "החייאה - 15 Robux",
		ReviveUsed       = "כבר השתמשת בהחייאה הסבב",
		SpectateBtn      = "מעבר לצפייה",
		LobbyBtn         = "חזרה ללובי",
		WaitingForRound  = "ממתין לסיום הסבב...",
	},
	Combat = {
		Hit              = "פגיעה!",
		Killed           = "הרגת %s!",
		OutOfRange       = "רחוק מדי",
		OnCooldown       = "ממתין...",
		WeaponNotOwned   = "אינך מחזיק בנשק",
		UnderLeveled     = "הנשק חלש מדי לחיה הזו",
	},
	Notifications = {
		Welcome          = "ברוכים הבאים!",
		FirstRound       = "המשחק הראשון שלך - בהצלחה!",
		ShotgunUnlocked  = "רובה הציד נפתח לצמיתות!",
		PurchaseFailed   = "הרכישה נכשלה - נסה שוב",
		SaveFailed       = "שמירה נכשלה - נסה להתחבר מחדש",
		ServerOnly       = "פעולה זו זמינה רק בצד השרת",
	},
	Animals = {
		Dog              = "כלב",
		Wolf             = "זאב",
		Bear             = "דוב",
		Lion             = "אריה",
	},
	Weapons = {
		Stick            = "מקל",
		Spear            = "חנית",
		Knife            = "סכין",
		Pistol           = "אקדח",
		Shotgun          = "רובה ציד",
	},
}
